// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNA5-uiWemRFCzBfDS707wQ1nsjonkV3Q',
    appId: '1:435140836187:web:10e67dfe2d7c86df43f87e',
    messagingSenderId: '435140836187',
    projectId: 'pulse-post-8b06a',
    authDomain: 'pulse-post-8b06a.firebaseapp.com',
    storageBucket: 'pulse-post-8b06a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjVygWQB5FivTJp70hGQbO-C6a02Jti4A',
    appId: '1:435140836187:android:8957bb4e22da51de43f87e',
    messagingSenderId: '435140836187',
    projectId: 'pulse-post-8b06a',
    storageBucket: 'pulse-post-8b06a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_U0fJaLLa0zPXPR3u9HeRKhr2ggN1900',
    appId: '1:435140836187:ios:16e88494f7c7cc8443f87e',
    messagingSenderId: '435140836187',
    projectId: 'pulse-post-8b06a',
    storageBucket: 'pulse-post-8b06a.firebasestorage.app',
    iosBundleId: 'com.example.ziyaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_U0fJaLLa0zPXPR3u9HeRKhr2ggN1900',
    appId: '1:435140836187:ios:16e88494f7c7cc8443f87e',
    messagingSenderId: '435140836187',
    projectId: 'pulse-post-8b06a',
    storageBucket: 'pulse-post-8b06a.firebasestorage.app',
    iosBundleId: 'com.example.ziyaProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNA5-uiWemRFCzBfDS707wQ1nsjonkV3Q',
    appId: '1:435140836187:web:45c3edf3892e270143f87e',
    messagingSenderId: '435140836187',
    projectId: 'pulse-post-8b06a',
    authDomain: 'pulse-post-8b06a.firebaseapp.com',
    storageBucket: 'pulse-post-8b06a.firebasestorage.app',
  );
}
